---
- name: Configure web server
  hosts: webservers
  become: true
- import_playbook: playbooks/packages.yml
- import_playbook: playbooks/certs&auth.yml
- import_playbook: playbooks/website.yml
- import_playbook: playbooks/prometheus_grafana.yml
